# Generated by Django 5.2.9 on 2026-01-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('advance', models.CharField(max_length=40, null=True)),
                ('location', models.TextField(null=True)),
                ('lunch', models.CharField(max_length=10, null=True)),
                ('dinner', models.CharField(max_length=10, null=True)),
                ('extra_meals', models.TextField(null=True)),
            ],
        ),
    ]
