# Generated by Django 5.2.9 on 2026-01-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
