# Generated by Django 5.2.9 on 2026-01-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='data',
            new_name='date',
        ),
    ]
